id: I26B14B46
legacy_id: P000462
ocr_import_info:
  bdrc_scan_id: W00KG01602
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T21:34:55'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T11:30:10.894603+00:00'
last_modified: 2022-08-29 19:30:38.927442
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG01602
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00KG01602
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འཕགས་པ་མཚན་ཡང་དག་པར་བརྗོད་པའི་མཚན་གྱི་སྔགས་དོན་གཟིགས་པའི་རྣམ་པར་བཤད་པ།
  author: སློབ་དཔོན་དཔལ་ལྡན་བྱང་ཆུབ།
statistics:
  ocr_word_mean_confidence_index: 0.4405694243894316
  ocr_word_median_confidence_index: 0.36000001430511475
quality: null
bases:
  I00KG02840:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG02840
      total_pages: 194
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG02840.txt
    statistics:
      ocr_word_median_confidence_index: 0.36000001430511475
      ocr_word_mean_confidence_index: 0.4405694243894316
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
